### ISSUE TITLE
Dropdown for User Hook 

### ISSUE THREAD

**Issue by ellongley** [lsst-camera-dh/EO-plotsDisplays#10]
Create dropdown for enabling, disabling and setting the user hook. Look into how the user code could be refreshed without restarting the app (if possible!)

**Comment by richardxdubois** [comment]
While looking at the user hook - also think out how the hook finds data in the various configurations. Emulation mode may be trickiest.

**Comment by ellongley** [comment]
Additionally add an option to refresh any changes to the hook.

**Comment by richardxdubois** [comment]
It's a button, but done.
