### ISSUE TITLE
Error handling: runs that do not include all EO tests

### ISSUE THREAD

**Issue by ellongley** [lsst-camera-dh/EO-plotsDisplays#15]
Add handling of the case where the run selected does not include all EO tests.  Use this as practice/brainstorming for other error handling.

**Comment by richardxdubois** [comment]
I've added a try/except for missing tests in the heatmap. It prints a warning message and reverts to the previous test.

Still need to handle missing tests in the per raft run plots app.

**Comment by richardxdubois** [comment]
Done. Switches test if current test vanished in new run.
