### ISSUE TITLE
Check Timing of Caching FP Version 

### ISSUE THREAD

**Issue by ellongley** [lsst-camera-dh/EO-plotsDisplays#19]
Check if it is possible/ saves time to cache the FP version of the ColumnDataSource upon return from other modes. It's slow to build from scratch but we have to eat that time every time we update the test quantity, so may not be a big win.

**Comment by richardxdubois** [comment]
I haven't figured out how to attach cProfile to the app in server mode. If that persists, maybe it will suffice to put in calls to a timer at key places in the code.

**Comment by richardxdubois** [comment]
I've written the new get_EO_analysis_results function to get all tests at once. A quick timing test shows it takes (only) twice as long to get all the tests as to get one. But it doesn't seem to eat up that much time. I suspect I need to do more timing tests to see where time is going. I *thought* it was in fetching the results.

**Comment by richardxdubois** [comment]
Some timing:

On entry: (2 rafts)
Timing: s  3.1235880851745605  r  21.688016176223755  h  21.695491075515747  d  21.71114206314087  t  8.12886929512024

After loading 15 rafts:

Timing: s  1.7522802352905273  r  129.1398482322693  h  129.1535623073578  d  129.1670482158661  t  69.30400490760803

All the time is going into setting up the data (the "r" step). I have integrated all the time grabbing test quantities in "t" - which looks like about 1/3-1/2 the time. "h" and "d" are the heatmap and making the layout. Negligible.

 So the eT db queries are significant, but not the whole story.

**Comment by richardxdubois** [comment]
Turns out the rest of the time is in getting the raft content via exploreRaft ("h_ccd"):

Timing: s  2.377347946166992  r  27.557748794555664  h  27.56582808494568  d  27.582585096359253  t  11.372244596481323  h_ccd  13.807121753692627

**Comment by richardxdubois** [comment]
and one more bit: 4.6 sec for getting the CCD content (h_ccd), and 2.4 secs to figure out the time of the run used (tr), to check when to get the CCD content (since it has been seen to change with time). 

Timing:   s  2.354713201522827  r  24.147578954696655  h  24.160510063171387  d  24.17582106590271  t  12.314836978912354  h_ccd  4.649724245071411  tr 2.4312520027160645

 So we have 3 things to think about caching - the test quantities, the CCD content (and when to ask for).

**Comment by richardxdubois** [comment]
Good progress here. I've made caches for the test quantities and CCD content. Initialization for 15 raft emulation mode is about 20 secs. Requesting a different test quantity for the same emulation takes 0.3 sec or so. I suppose at some point we may want to allow the user to clear the cache, if they are running out of memory.

 We still need to some checking that nothing got lost in the translation - ie the test results that are coming up are the right ones...

**Comment by richardxdubois** [comment]
Done
