### ISSUE TITLE
Testing and Documentation of Bokeh Plots in Non-Server Mode

### ISSUE THREAD

**Issue by ellongley** [lsst-camera-dh/EO-plotsDisplays#24]
Ref: JIRA Issue LSSTTD-1342

Need to test and document how to produce Bokeh plots without launching Bokeh i.e. in a batch mode. This is a prerequisite to producing the pngs as an analysis step in the EO traveler.

**Comment by richardxdubois** [comment]
This is trivial. One just runs the script from the CLI and uses export_png() as the output mechanism.
