### ISSUE TITLE
Change Line Thickness 

### ISSUE THREAD

**Issue by ellongley** [lsst-camera-dh/EO-plotsDisplays#27]
It was suggested that it would be easier to see the colors on the heatmap if the lines delineating the amplifiers were thinner.  Additionally it would be good to have a different ( thicker ) line to show the CCD / Raft boundaries.

**Comment by richardxdubois** [comment]
I played with this a little. line_width is the parameter to add to the heatmap.rect. But since we draw the amps on top, it's not clear to me we'd see the CCD and raft boundaries. Unless we undersize the amps to reveal the boundaries.
