### ISSUE TITLE
Changes to Reading in Emulation Config File 

### ISSUE THREAD

**Issue by ellongley** [lsst-camera-dh/EO-plotsDisplays#7]
Currently you can only read in the emulation config file from the CWD.

**Comment by ellongley** [comment]
For security reasons javascript will not return the full file path of the local file to be uploaded. 

Couple items attempted to get around this but with no success: 

Creating a temporary path as described here: https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav 

Requesting access to file system as described here: https://www.html5rocks.com/en/tutorials/file/filesystem/ 

One temporary change that might be possible is to include a directory in this repo to hold input files and then add a relative path in the code.

**Comment by richardxdubois** [comment]
I think this is the example I saw for reading the file into memory and then into a dataframe (see the answer):

https://stackoverflow.com/questions/49752809/bokeh-display-local-file-in-datatable-widget

**Comment by richardxdubois** [comment]
Done!
